import fs from 'fs';import path from 'path';
const root=process.cwd(), out=path.join(root,'dist');fs.rmSync(out,{recursive:true,force:true});fs.mkdirSync(out,{recursive:true});fs.cpSync(path.join(root,'public'),out,{recursive:true});
const cats=['History','Geography','Economics','Indian Constitution','Kerala Governance & Administration','Life Science','Physics','Chemistry','Arts, Literature, Culture & Sports','Computer','Education Policies, Acts & Commissions','Current Affairs','Arithmetic & Reasoning','English','Regional Language'];
const subs={History:['Kerala History','Indian History','World History'],Geography:['Kerala Geography','Indian Geography','World & General Geography'],Economics:['Economic Concepts','Indian Economy','Kerala Economy']};
const slug=s=>s.toLowerCase().replace(/&/g,'and').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
function parse(f){let t=fs.readFileSync(f,'utf8'),m=t.match(/^---\n([\s\S]*?)\n---\n?([\s\S]*)$/);if(!m)return null;let d={},key='';for(const l of m[1].split('\n')){let x=l.match(/^([\w_]+):\s*(.*)$/);if(x){key=x[1];d[key]=x[2].replace(/^['"]|['"]$/g,'');if(key==='tags')d.tags=[]}else if(/^\s*-\s+/.test(l)&&key==='tags')d.tags.push(l.replace(/^\s*-\s+/,'').replace(/^['"]|['"]$/g,''))}d.body=m[2];d.slug=slug(d.title||path.basename(f,'.md'));return d}
const files=fs.readdirSync(path.join(root,'content')).filter(x=>x.endsWith('.md'));const items=files.map(x=>parse(path.join(root,'content',x))).filter(Boolean);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function md(s){return s.split(/\n\n+/).map(b=>{b=b.trim();if(!b)return'';if(/^### /.test(b))return`<h3>${esc(b.slice(4))}</h3>`;if(/^## /.test(b))return`<h2>${esc(b.slice(3))}</h2>`;if(/^# /.test(b))return`<h1>${esc(b.slice(2))}</h1>`;if(/^!\[/.test(b)){let m=b.match(/^!\[(.*?)\]\((.*?)\)$/s);if(m)return`<img src="${esc(m[2])}" alt="${esc(m[1])}">`}if(/^(- |\* )/m.test(b))return'<ul>'+b.split('\n').map(x=>`<li>${esc(x.replace(/^[-*]\s+/,''))}</li>`).join('')+'</ul>';return`<p>${esc(b).replace(/\*\*(.*?)\*\*/g,'<strong>$1</strong>').replace(/\n/g,'<br>')}</p>`}).join('\n')}
function sidebar(active=''){return`<aside class="sidebar"><div class="brand"><div class="mark">K</div><div><strong>Kerala PSC</strong><small>Focused Notes</small></div></div><nav class="nav"><a href="/" class="${active==='Home'?'active':''}">⌂ Home</a><div class="nav-label">Syllabus</div>${cats.map(c=>subs[c]?`<details ${active===c?'open':''}><summary>${esc(c)} <span class="chev">›</span></summary><a href="/category/${slug(c)}/">All ${esc(c)}</a>${subs[c].map(s=>`<a href="/category/${slug(c)}/${slug(s)}/">${esc(s)}</a>`).join('')}</details>`:`<a class="${active===c?'active':''}" href="/category/${slug(c)}/">${esc(c)}</a>`).join('')}</nav></aside>`}
function shell(title,desc,body,active=''){return`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)}</title><meta name="description" content="${esc(desc)}"><link rel="stylesheet" href="/assets/style.css"></head><body><div class="app">${sidebar(active)}<main><div class="topbar"><button class="mobile">☰</button><div class="search"><span>⌕</span><input id="search" placeholder="Search this page…"></div></div>${body}</main></div><script src="/assets/app.js"></script></body></html>`}
function write(rel,html){let p=path.join(out,rel);fs.mkdirSync(path.dirname(p),{recursive:true});fs.writeFileSync(p,html)}
const cards=cats.map(c=>{let n=items.filter(x=>x.category===c).length;return`<a class="card" data-search="${esc(c.toLowerCase())}" href="/category/${slug(c)}/"><div class="icon">${esc(c[0])}</div><h3>${esc(c)}</h3><p>${subs[c]?subs[c].join(' · '):'Browse syllabus-based study material'}</p><div class="count">${n} ${n===1?'entry':'entries'}</div></a>`}).join('');
write('index.html',shell('Kerala PSC Notes | Syllabus-Based Study Material','Kerala PSC notes organised by syllabus category and topic for focused preparation.',`<section class="hero"><div class="eyebrow">Syllabus-based preparation</div><h1>Kerala PSC Notes</h1><p>Focused study material, organised exactly where you expect it. Choose a subject and start revising.</p></section><div class="section-head"><div><h2>Browse subjects</h2><p>Built around the Kerala PSC syllabus.</p></div></div><section class="grid">${cards}</section>`,'Home'));
for(const c of cats){let ci=items.filter(x=>x.category===c);let subnav=subs[c]?`<section class="grid">${subs[c].map(s=>`<a class="card" data-search="${s.toLowerCase()}" href="/category/${slug(c)}/${slug(s)}/"><div class="icon">${s[0]}</div><h3>${s}</h3><p>Browse ${s} material</p></a>`).join('')}</section>`:'';let rows=ci.map(x=>`<a class="article-row" data-search="${esc((x.title+' '+(x.tags||[]).join(' ')).toLowerCase())}" href="/content/${x.slug}/"><h3>${esc(x.title)}</h3><div class="meta">${esc(x.subcategory||c)}</div><div class="tags">${(x.tags||[]).map(t=>`<span class="tag">${esc(t)}</span>`).join('')}</div></a>`).join('')||'<div class="empty">No content added yet.</div>';write(`category/${slug(c)}/index.html`,shell(`${c} | Kerala PSC Notes`,`Kerala PSC ${c} study material organised for quick revision.`,`<div class="breadcrumb"><a href="/">Home</a> / ${esc(c)}</div><div class="section-head"><div><h2>${esc(c)}</h2><p>${subs[c]?'Choose a subcategory or browse everything below.':'Browse all material in this category.'}</p></div></div>${subnav}<div class="section-head"><div><h2>All content</h2></div></div><div class="article-list">${rows}</div>`,c));if(subs[c])for(const s of subs[c]){let si=ci.filter(x=>x.subcategory===s),r=si.map(x=>`<a class="article-row" data-search="${esc((x.title+' '+(x.tags||[]).join(' ')).toLowerCase())}" href="/content/${x.slug}/"><h3>${esc(x.title)}</h3><div class="tags">${(x.tags||[]).map(t=>`<span class="tag">${esc(t)}</span>`).join('')}</div></a>`).join('')||'<div class="empty">No content added yet.</div>';write(`category/${slug(c)}/${slug(s)}/index.html`,shell(`${s} | Kerala PSC Notes`,`Kerala PSC ${s} study material and revision notes.`,`<div class="breadcrumb"><a href="/">Home</a> / <a href="/category/${slug(c)}/">${esc(c)}</a> / ${esc(s)}</div><div class="section-head"><div><h2>${esc(s)}</h2><p>${esc(c)}</p></div></div><div class="article-list">${r}</div>`,c))}}
for(const x of items)write(`content/${x.slug}/index.html`,shell(x.seo_title||x.title,x.meta_description||'',`<div class="breadcrumb"><a href="/">Home</a> / <a href="/category/${slug(x.category)}/">${esc(x.category)}</a>${x.subcategory?` / ${esc(x.subcategory)}`:''}</div><article class="content"><div class="eyebrow">${esc(x.category)}</div>${md(x.body)}<div class="tags">${(x.tags||[]).map(t=>`<span class="tag">${esc(t)}</span>`).join('')}</div></article>`,x.category));
console.log(`Built ${items.length} content entries.`)
